# FILENAME
# one_click_azure.yml
#
# DESCRIPTION
# Sample playbook used in conjuction with terraform one_click deployment scenario in Azure
# https://github.com/PaloAltoNetworks/terraform-templates/one_click_multicloud
#
# REQUIREMENTS
# see https://github.com/PaloAltoNetworks/terraform-templates/one_click_multicloud/README.md
#
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    # Use a template from a URL
    - name: create a global service for TCP 221
      panos_object:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        serviceobject: 'service-tcp-221'
        destination_port: '221'
        protocol: 'tcp'
        description: 'ssh on 221'
    - name: Create NAT rule for Web SSH
      panos_nat_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: "WebSSH"
        source_zone: ["Untrust"]
        destination_zone: "Untrust"
        source_ip: ["any"]
        destination_ip: ["10.5.1.4"]
        service: "service-tcp-221"
        snat_type: "dynamic-ip-and-port"
        snat_interface: "ethernet1/2"
        dnat_address: "10.5.3.5"
        dnat_port: "22"
        commit: "False"
    - name: Wordpress NAT
      panos_nat_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: "WPNAT"
        source_zone: ["Untrust"]
        destination_zone: "Untrust"
        source_ip: ["any"]
        destination_ip: ["10.5.1.4"]
        service: "service-http"
        snat_type: "dynamic-ip-and-port"
        snat_interface: "ethernet1/2"
        dnat_address: "10.5.3.5"
        dnat_port: "80"
        commit: "False"
    - name: Outbound NAT
      panos_nat_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: "NATAllOut"
        source_zone: ["Trust"]
        destination_zone: "Untrust"
        source_ip: ["any"]
        destination_ip: ["any"]
        snat_type: "dynamic-ip-and-port"
        snat_interface: "ethernet1/1"
        commit: "False"
    - name: add a rule to allow HTTP
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'Web traffic'
        service: 'service-http'
        description: 'Allow HTTP traffic'
        source_zone: ['Untrust']
        destination_zone: ['Trust']
        action: 'allow'
        commit: "False"
    - name: SSH Inbound
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'SSH traffic'
        application: ['ping','ssh']
        description: 'Allow SSH traffic'
        source_zone: ['Untrust']
        destination_zone: ['Trust']
        action: 'allow'
        commit: "False"
    - name: SSH 221 Inbound
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'SSH 221 traffic'
        application: ['ping','ssh']
        service: 'service-tcp-221'
        description: 'Allow SSH traffic'
        source_zone: ['Untrust']
        destination_zone: ['Trust']
        action: 'allow'
        commit: "False"
    - name: Log default deny
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'Log default deny'
        description: 'Allow SSH traffic'
        source_zone: ['any']
        destination_zone: ['any']
        action: 'deny'
        commit: "True"

